name: Pause Instances Workflow

on:
  push:
    branches:
      - main

jobs:
  pause-instances:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5.1.1
      with:
        python-version: '3.x'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run pause instances script
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_PWD: ${{ secrets.CLIENT_PWD }}
      run: |
        python pause_instances.py